name: PR Description Template

on:
  pull_request:
    types: [opened, edited, synchronize]  # Trigger when a PR is created, edited, or updated

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
